
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    [System.Flags]
    public enum ENumericNoticeType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 自己
        /// </summary>
        Self = 1,
        /// <summary>
        /// 全体
        /// </summary>
        Broadcast = 2,
        /// <summary>
        /// 除自己外
        /// </summary>
        BroadcastWithoutSelf = 3,
    }

} 

