
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public abstract partial class NumericValueLimitData : Luban.BeanBase
    {
        public NumericValueLimitData(ByteBuf _buf) 
        {

            EndInit();
        }

        public static NumericValueLimitData DeserializeNumericValueLimitData(ByteBuf _buf)
        {
            switch (_buf.ReadInt())
            {
                case NumericValueLimitNumber.__ID__: return new NumericValueLimitNumber(_buf);
                case NumericValueLimitNumeric.__ID__: return new NumericValueLimitNumeric(_buf);
                default: throw new SerializationException();
            }
        }

    

        public virtual void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "}";
        }

        partial void EndRef();
    }

}

