
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    [System.Flags]
    public enum ENumericValueLimitType
    {
        /// <summary>
        /// 数字
        /// </summary>
        Number = 0,
        /// <summary>
        /// 数值
        /// </summary>
        Numeric = 1,
    }

} 

