
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class NumericValueAffectConfig : Luban.BeanBase
    {
        public NumericValueAffectConfig(ByteBuf _buf) 
        {
            Id = (ENumericType)_buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Affects = new System.Collections.Generic.List<ENumericType>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ENumericType _e0;  _e0 = (ENumericType)_buf.ReadInt(); Affects.Add(_e0);}}

            EndInit();
        }

        public static NumericValueAffectConfig DeserializeNumericValueAffectConfig(ByteBuf _buf)
        {
            return new NumericValueAffectConfig(_buf);
        }

        public readonly ENumericType Id;
        public readonly System.Collections.Generic.List<ENumericType> Affects;
    
        public const int __ID__ = -62272677;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "affects:" + Luban.StringUtil.CollectionToString(Affects) + ","
            + "}";
        }

        partial void EndRef();
    }

}

