
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class NumericValueLimitConfigCategory : Singleton<NumericValueLimitConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<ENumericType, NumericValueLimitConfig> _dataMap;
        private readonly List<NumericValueLimitConfig> _dataList;
        
        public NumericValueLimitConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<ENumericType, NumericValueLimitConfig>();
            _dataList = new List<NumericValueLimitConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                NumericValueLimitConfig _v;
                _v = NumericValueLimitConfig.DeserializeNumericValueLimitConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<ENumericType, NumericValueLimitConfig> GetAll() => _dataMap;
        public Dictionary<ENumericType, NumericValueLimitConfig> DataMap => _dataMap;
        public List<NumericValueLimitConfig> DataList => _dataList;

        public NumericValueLimitConfig GetOrDefault(ENumericType key) => _dataMap.GetValueOrDefault(key);

        public NumericValueLimitConfig Get(ENumericType key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

