
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class NumericValueAffectConfigCategory : Singleton<NumericValueAffectConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<ENumericType, NumericValueAffectConfig> _dataMap;
        private readonly List<NumericValueAffectConfig> _dataList;
        
        public NumericValueAffectConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<ENumericType, NumericValueAffectConfig>();
            _dataList = new List<NumericValueAffectConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                NumericValueAffectConfig _v;
                _v = NumericValueAffectConfig.DeserializeNumericValueAffectConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<ENumericType, NumericValueAffectConfig> GetAll() => _dataMap;
        public Dictionary<ENumericType, NumericValueAffectConfig> DataMap => _dataMap;
        public List<NumericValueAffectConfig> DataList => _dataList;

        public NumericValueAffectConfig GetOrDefault(ENumericType key) => _dataMap.GetValueOrDefault(key);

        public NumericValueAffectConfig Get(ENumericType key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

