
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class NumericDemoConfig : Luban.BeanBase
    {
        public NumericDemoConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Numeric = NumericConfigData.DeserializeNumericConfigData(_buf);

            EndInit();
        }

        public static NumericDemoConfig DeserializeNumericDemoConfig(ByteBuf _buf)
        {
            return new NumericDemoConfig(_buf);
        }

        /// <summary>
        /// id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// k
        /// </summary>
        public readonly NumericConfigData Numeric;
    
        public const int __ID__ = 47825362;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            Numeric?.ResolveRef();
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "numeric:" + Numeric + ","
            + "}";
        }

        partial void EndRef();
    }

}

