
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class NumericConfigData : Luban.BeanBase
    {
        public NumericConfigData(ByteBuf _buf) 
        {
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ConfigData = new System.Collections.Generic.Dictionary<ENumericType, long>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { ENumericType _k0;  _k0 = (ENumericType)_buf.ReadInt(); long _v0;  _v0 = _buf.ReadLong();     ConfigData.Add(_k0, _v0);}}

            EndInit();
        }

        public static NumericConfigData DeserializeNumericConfigData(ByteBuf _buf)
        {
            return new NumericConfigData(_buf);
        }

        /// <summary>
        /// 配置数据
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<ENumericType, long> ConfigData;
    
        public const int __ID__ = -1520828199;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "configData:" + Luban.StringUtil.CollectionToString(ConfigData) + ","
            + "}";
        }

        partial void EndRef();
    }

}

