
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class NumericValueLimitNumeric : NumericValueLimitData
    {
        public NumericValueLimitNumeric(ByteBuf _buf)  : base(_buf) 
        {
            Value = (ENumericType)_buf.ReadInt();

            EndInit();
        }

        public static NumericValueLimitNumeric DeserializeNumericValueLimitNumeric(ByteBuf _buf)
        {
            return new NumericValueLimitNumeric(_buf);
        }

        /// <summary>
        /// 值
        /// </summary>
        public readonly ENumericType Value;
    
        public const int __ID__ = 1873229686;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef()
        {
            base.ResolveRef();
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "value:" + Value + ","
            + "}";
        }

        partial void EndRef();
    }

}

